version: '3'
services:
  email-parser:
    build: .
    image: email-parser
    container_name: email-parser-container
    ports:
      - "5000:5000"
    volumes:
      - ./output.csv:/app/output.csv
